### ISSUE TITLE
Returning wrong zone?

### ISSUE THREAD

**Issue by e5k** [Turbo87/utm#63] opened 2020-12-14 09:25 UTC
Hi,

I am trying to get the UTM zone for given coordinates (i.e. Taal volcano) using v0.7, Python 3.9 on Anaconda/OSX. It should return `51 P` but returns `50 L`. Any idea?
Cheers

S

```python
lat=14.0107554
lon=120.9979889

zone = utm.from_latlon(lat,lon)

zone
(609326.0410868623, 9088147.638740664, 50, 'L')
```

<img width="536" alt="image" src="https://user-images.githubusercontent.com/16320236/102063591-31843680-3e31-11eb-9358-4b7866a17258.png">

**Comment by eumiro** [comment] 2020-12-18 21:41
Just to compare with Python 3.9.0 and the current git clone:

```python
>>> import utm
>>> lat=14.0107554
>>> lon=120.9979889
>>> utm.from_latlon(lat,lon)
(283772.21524068655, 1549830.6652980775, 51, 'P')
```

**Comment by e5k** [comment] 2020-12-19 05:19
Ok my bad, I had the pip version, thanks for trying. Maybe worth updating it there?

**Comment by bartvanandel** [comment] 2024-12-15 12:51
We'll need a release for sure, but since the problem is fixed in src, I'm gonna close this issue.

**Closed by bartvanandel** 2024-12-15 12:51 UTC
